// Code generated by entc, DO NOT EDIT.

package database

import (
	"time"

	"github.com/naturalselectionlabs/pregod/common/database/schema"
	"github.com/naturalselectionlabs/pregod/common/database/transfer"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	transferMixin := schema.Transfer{}.Mixin()
	transferMixinFields0 := transferMixin[0].Fields()
	_ = transferMixinFields0
	transferFields := schema.Transfer{}.Fields()
	_ = transferFields
	// transferDescCreatedAt is the schema descriptor for created_at field.
	transferDescCreatedAt := transferMixinFields0[0].Descriptor()
	// transfer.DefaultCreatedAt holds the default value on creation for the created_at field.
	transfer.DefaultCreatedAt = transferDescCreatedAt.Default.(func() time.Time)
	// transferDescUpdatedAt is the schema descriptor for updated_at field.
	transferDescUpdatedAt := transferMixinFields0[1].Descriptor()
	// transfer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transfer.DefaultUpdatedAt = transferDescUpdatedAt.Default.(func() time.Time)
	// transfer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transfer.UpdateDefaultUpdatedAt = transferDescUpdatedAt.UpdateDefault.(func() time.Time)
}
