// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package enssubgraph

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetEnsNameByNameHashDomainsDomain includes the requested fields of the GraphQL type Domain.
type GetEnsNameByNameHashDomainsDomain struct {
	Id              string                                                  `json:"id"`
	Name            string                                                  `json:"name"`
	LabelName       string                                                  `json:"labelName"`
	Labelhash       string                                                  `json:"labelhash"`
	Owner           GetEnsNameByNameHashDomainsDomainOwnerAccount           `json:"owner"`
	ResolvedAddress GetEnsNameByNameHashDomainsDomainResolvedAddressAccount `json:"resolvedAddress"`
	Resolver        GetEnsNameByNameHashDomainsDomainResolver               `json:"resolver"`
}

// GetId returns GetEnsNameByNameHashDomainsDomain.Id, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetId() string { return v.Id }

// GetName returns GetEnsNameByNameHashDomainsDomain.Name, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetName() string { return v.Name }

// GetLabelName returns GetEnsNameByNameHashDomainsDomain.LabelName, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetLabelName() string { return v.LabelName }

// GetLabelhash returns GetEnsNameByNameHashDomainsDomain.Labelhash, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetLabelhash() string { return v.Labelhash }

// GetOwner returns GetEnsNameByNameHashDomainsDomain.Owner, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetOwner() GetEnsNameByNameHashDomainsDomainOwnerAccount {
	return v.Owner
}

// GetResolvedAddress returns GetEnsNameByNameHashDomainsDomain.ResolvedAddress, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetResolvedAddress() GetEnsNameByNameHashDomainsDomainResolvedAddressAccount {
	return v.ResolvedAddress
}

// GetResolver returns GetEnsNameByNameHashDomainsDomain.Resolver, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomain) GetResolver() GetEnsNameByNameHashDomainsDomainResolver {
	return v.Resolver
}

// GetEnsNameByNameHashDomainsDomainOwnerAccount includes the requested fields of the GraphQL type Account.
type GetEnsNameByNameHashDomainsDomainOwnerAccount struct {
	Id string `json:"id"`
}

// GetId returns GetEnsNameByNameHashDomainsDomainOwnerAccount.Id, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomainOwnerAccount) GetId() string { return v.Id }

// GetEnsNameByNameHashDomainsDomainResolvedAddressAccount includes the requested fields of the GraphQL type Account.
type GetEnsNameByNameHashDomainsDomainResolvedAddressAccount struct {
	Id string `json:"id"`
}

// GetId returns GetEnsNameByNameHashDomainsDomainResolvedAddressAccount.Id, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomainResolvedAddressAccount) GetId() string { return v.Id }

// GetEnsNameByNameHashDomainsDomainResolver includes the requested fields of the GraphQL type Resolver.
type GetEnsNameByNameHashDomainsDomainResolver struct {
	Id string `json:"id"`
}

// GetId returns GetEnsNameByNameHashDomainsDomainResolver.Id, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashDomainsDomainResolver) GetId() string { return v.Id }

// GetEnsNameByNameHashResponse is returned by GetEnsNameByNameHash on success.
type GetEnsNameByNameHashResponse struct {
	Domains []GetEnsNameByNameHashDomainsDomain `json:"domains"`
}

// GetDomains returns GetEnsNameByNameHashResponse.Domains, and is useful for accessing the field via an interface.
func (v *GetEnsNameByNameHashResponse) GetDomains() []GetEnsNameByNameHashDomainsDomain {
	return v.Domains
}

// __GetEnsNameByNameHashInput is used internally by genqlient
type __GetEnsNameByNameHashInput struct {
	Namehash string `json:"namehash"`
}

// GetNamehash returns __GetEnsNameByNameHashInput.Namehash, and is useful for accessing the field via an interface.
func (v *__GetEnsNameByNameHashInput) GetNamehash() string { return v.Namehash }

func GetEnsNameByNameHash(
	ctx context.Context,
	client graphql.Client,
	namehash string,
) (*GetEnsNameByNameHashResponse, error) {
	req := &graphql.Request{
		OpName: "GetEnsNameByNameHash",
		Query: `
query GetEnsNameByNameHash ($namehash: ID!) {
	domains(where: {id:$namehash}) {
		id
		name
		labelName
		labelhash
		owner {
			id
		}
		resolvedAddress {
			id
		}
		resolver {
			id
		}
	}
}
`,
		Variables: &__GetEnsNameByNameHashInput{
			Namehash: namehash,
		},
	}
	var err error

	var data GetEnsNameByNameHashResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
