// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package lens

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetDefaultProfileDefaultProfile includes the requested fields of the GraphQL type Profile.
type GetDefaultProfileDefaultProfile struct {
	Id string `json:"id"`
}

// GetId returns GetDefaultProfileDefaultProfile.Id, and is useful for accessing the field via an interface.
func (v *GetDefaultProfileDefaultProfile) GetId() string { return v.Id }

// GetDefaultProfileResponse is returned by GetDefaultProfile on success.
type GetDefaultProfileResponse struct {
	DefaultProfile GetDefaultProfileDefaultProfile `json:"defaultProfile"`
}

// GetDefaultProfile returns GetDefaultProfileResponse.DefaultProfile, and is useful for accessing the field via an interface.
func (v *GetDefaultProfileResponse) GetDefaultProfile() GetDefaultProfileDefaultProfile {
	return v.DefaultProfile
}

// GetFollowersFollowersPaginatedFollowersResult includes the requested fields of the GraphQL type PaginatedFollowersResult.
type GetFollowersFollowersPaginatedFollowersResult struct {
	PageInfo GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo `json:"pageInfo"`
}

// GetPageInfo returns GetFollowersFollowersPaginatedFollowersResult.PageInfo, and is useful for accessing the field via an interface.
func (v *GetFollowersFollowersPaginatedFollowersResult) GetPageInfo() GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo {
	return v.PageInfo
}

// GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo includes the requested fields of the GraphQL type PaginatedResultInfo.
type GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo struct {
	Prev       string `json:"prev"`
	Next       string `json:"next"`
	TotalCount int    `json:"totalCount"`
}

// GetPrev returns GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo.Prev, and is useful for accessing the field via an interface.
func (v *GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo) GetPrev() string {
	return v.Prev
}

// GetNext returns GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo.Next, and is useful for accessing the field via an interface.
func (v *GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo) GetNext() string {
	return v.Next
}

// GetTotalCount returns GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo.TotalCount, and is useful for accessing the field via an interface.
func (v *GetFollowersFollowersPaginatedFollowersResultPageInfoPaginatedResultInfo) GetTotalCount() int {
	return v.TotalCount
}

// GetFollowersResponse is returned by GetFollowers on success.
type GetFollowersResponse struct {
	Followers GetFollowersFollowersPaginatedFollowersResult `json:"followers"`
}

// GetFollowers returns GetFollowersResponse.Followers, and is useful for accessing the field via an interface.
func (v *GetFollowersResponse) GetFollowers() GetFollowersFollowersPaginatedFollowersResult {
	return v.Followers
}

// GetFollowingFollowingPaginatedFollowingResult includes the requested fields of the GraphQL type PaginatedFollowingResult.
type GetFollowingFollowingPaginatedFollowingResult struct {
	PageInfo GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo `json:"pageInfo"`
}

// GetPageInfo returns GetFollowingFollowingPaginatedFollowingResult.PageInfo, and is useful for accessing the field via an interface.
func (v *GetFollowingFollowingPaginatedFollowingResult) GetPageInfo() GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo {
	return v.PageInfo
}

// GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo includes the requested fields of the GraphQL type PaginatedResultInfo.
type GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo struct {
	Prev       string `json:"prev"`
	Next       string `json:"next"`
	TotalCount int    `json:"totalCount"`
}

// GetPrev returns GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo.Prev, and is useful for accessing the field via an interface.
func (v *GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo) GetPrev() string {
	return v.Prev
}

// GetNext returns GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo.Next, and is useful for accessing the field via an interface.
func (v *GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo) GetNext() string {
	return v.Next
}

// GetTotalCount returns GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo.TotalCount, and is useful for accessing the field via an interface.
func (v *GetFollowingFollowingPaginatedFollowingResultPageInfoPaginatedResultInfo) GetTotalCount() int {
	return v.TotalCount
}

// GetFollowingResponse is returned by GetFollowing on success.
type GetFollowingResponse struct {
	Following GetFollowingFollowingPaginatedFollowingResult `json:"following"`
}

// GetFollowing returns GetFollowingResponse.Following, and is useful for accessing the field via an interface.
func (v *GetFollowingResponse) GetFollowing() GetFollowingFollowingPaginatedFollowingResult {
	return v.Following
}

// __GetDefaultProfileInput is used internally by genqlient
type __GetDefaultProfileInput struct {
	Address string `json:"address"`
}

// GetAddress returns __GetDefaultProfileInput.Address, and is useful for accessing the field via an interface.
func (v *__GetDefaultProfileInput) GetAddress() string { return v.Address }

// __GetFollowersInput is used internally by genqlient
type __GetFollowersInput struct {
	ProfileId string `json:"profileId"`
}

// GetProfileId returns __GetFollowersInput.ProfileId, and is useful for accessing the field via an interface.
func (v *__GetFollowersInput) GetProfileId() string { return v.ProfileId }

// __GetFollowingInput is used internally by genqlient
type __GetFollowingInput struct {
	Address string `json:"address"`
}

// GetAddress returns __GetFollowingInput.Address, and is useful for accessing the field via an interface.
func (v *__GetFollowingInput) GetAddress() string { return v.Address }

func GetDefaultProfile(
	ctx context.Context,
	client graphql.Client,
	address string,
) (*GetDefaultProfileResponse, error) {
	req := &graphql.Request{
		OpName: "GetDefaultProfile",
		Query: `
query GetDefaultProfile ($address: EthereumAddress!) {
	defaultProfile(request: {ethereumAddress:$address}) {
		id
	}
}
`,
		Variables: &__GetDefaultProfileInput{
			Address: address,
		},
	}
	var err error

	var data GetDefaultProfileResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetFollowers(
	ctx context.Context,
	client graphql.Client,
	profileId string,
) (*GetFollowersResponse, error) {
	req := &graphql.Request{
		OpName: "GetFollowers",
		Query: `
query GetFollowers ($profileId: ProfileId!) {
	followers(request: {profileId:$profileId,limit:1}) {
		pageInfo {
			prev
			next
			totalCount
		}
	}
}
`,
		Variables: &__GetFollowersInput{
			ProfileId: profileId,
		},
	}
	var err error

	var data GetFollowersResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetFollowing(
	ctx context.Context,
	client graphql.Client,
	address string,
) (*GetFollowingResponse, error) {
	req := &graphql.Request{
		OpName: "GetFollowing",
		Query: `
query GetFollowing ($address: EthereumAddress!) {
	following(request: {address:$address,limit:1}) {
		pageInfo {
			prev
			next
			totalCount
		}
	}
}
`,
		Variables: &__GetFollowingInput{
			Address: address,
		},
	}
	var err error

	var data GetFollowingResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
