// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
