// Code generated by entc, DO NOT EDIT.

package transfer

import (
	"time"
)

const (
	// Label holds the string label denoting the transfer type in the database.
	Label = "transfer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTransactionHash holds the string denoting the transaction_hash field in the database.
	FieldTransactionHash = "transaction_hash"
	// FieldTransactionLogIndex holds the string denoting the transaction_log_index field in the database.
	FieldTransactionLogIndex = "transaction_log_index"
	// FieldAddressFrom holds the string denoting the address_from field in the database.
	FieldAddressFrom = "address_from"
	// FieldAddressTo holds the string denoting the address_to field in the database.
	FieldAddressTo = "address_to"
	// FieldTokenAddress holds the string denoting the token_address field in the database.
	FieldTokenAddress = "token_address"
	// FieldTokenID holds the string denoting the token_id field in the database.
	FieldTokenID = "token_id"
	// Table holds the table name of the transfer in the database.
	Table = "transfers"
)

// Columns holds all SQL columns for transfer fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTransactionHash,
	FieldTransactionLogIndex,
	FieldAddressFrom,
	FieldAddressTo,
	FieldTokenAddress,
	FieldTokenID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
