// Code generated by "stringer -type=TransferTag -linecomment"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransferTagEth-1]
	_ = x[TransferTagErc20-1]
	_ = x[TransferTagErc721-1]
	_ = x[TransferTagNFT-2]
	_ = x[TransferTagMirror-3]
	_ = x[TransferTagEns-3]
	_ = x[TransferTagGitcoin-3]
	_ = x[TransferTagPoap-3]
	_ = x[TransferTagSwap-10]
	_ = x[TransferTagDonation-10]
	_ = x[TransferTagDomain-10]
	_ = x[TransferTagSnapshot-10]
}

const (
	_TransferTag_name_0 = "ethnftmirror"
	_TransferTag_name_1 = "swap"
)

var (
	_TransferTag_index_0 = [...]uint8{0, 3, 6, 12}
)

func (i TransferTag) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _TransferTag_name_0[_TransferTag_index_0[i]:_TransferTag_index_0[i+1]]
	case i == 10:
		return _TransferTag_name_1
	default:
		return "TransferTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
